dense: dense.cpp
	g++ dense.cpp -o dense -pthread -lboost_program_options -lboost_filesystem -std=c++11 `pkg-config --cflags --libs opencv4`
sparse: sparse.cpp
	g++ sparse.cpp -o sparse -pthread -lboost_program_options -lboost_filesystem -std=c++11 `pkg-config --cflags --libs opencv4`